name: Check Latest GitHub Release and Upload to S3

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  check_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests packaging

      - name: Run Release Check Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: python check_releases.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ap-south-1

      - name: Check S3 and Upload New Release Files
        run: |
          BUCKET_NAME="myawsbucket9660551704"
          OUTPUT_DIR="output"

          if [ ! -d "$OUTPUT_DIR" ]; then
            echo "No output directory found. No releases were generated."
            exit 0
          fi

          find "$OUTPUT_DIR" -type f -name "*.json" | while read -r local_json_file; do
            repo_name=$(basename $(dirname "$local_json_file"))
            file_name=$(basename "$local_json_file")
            local_html_file="${local_json_file%.json}.html"
            html_file_name=$(basename "$local_html_file")
            s3_key_path="${repo_name}/${file_name}"

            echo "--------------------------------------------------"
            echo "Processing: ${repo_name}"
            echo "Checking for S3 object: s3://${BUCKET_NAME}/${s3_key_path}"

            # CORRECTED LOGIC: Use 'if ! command' to test for failure.
            if ! aws s3api head-object --bucket "$BUCKET_NAME" --key "$s3_key_path" >/dev/null 2>&1; then
              echo "Release version not found in S3. Uploading..."
              
              aws s3 cp "$local_json_file" "s3://${BUCKET_NAME}/${s3_key_path}"
              echo "✅ Uploaded ${file_name}"
              
              aws s3 cp "$local_html_file" "s3://${BUCKET_NAME}/${repo_name}/${html_file_name}"
              echo "✅ Uploaded ${html_file_name}"
            else
              echo "This release version is already present in S3. No action needed."
            fi
          done
          echo "--------------------------------------------------"
          echo "S3 release check complete."
