name: Check GitHub Releases

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  check_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This token is used to push changes back to the repository
          token: ${{ secrets.GH_PAT }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x fetchRebaseVersion.sh

      - name: Run release check script
        run: |
          ./fetchRebaseVersion.sh 
          cat R1.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      

