name: EC2 Deploy / Rollback by Index

on:
  workflow_dispatch:
    inputs:
      be_rollback_index:
        description: 'Pedigree-Vision-BE: 0=deploy latest, -1=skip, >0=rollback by N versions'
        required: true
        type: number
        default: 0
      ui_rollback_index:
        description: 'PedigreeVisionUI: 0=deploy latest, -1=skip, >0=rollback by N versions'
        required: true
        type: number
        default: 0
      models_rollback_index:
        description: 'DigitreeModels: 0=deploy latest, -1=skip, >0=rollback by N versions'
        required: true
        type: number
        default: 0

jobs:
  trigger_deploy_or_rollback:
    name: Trigger Deploy/Rollback on EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute Conditional Deploy/Rollback on EC2 Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            set -e # Stop the script if any command fails

            # The script logic inside the pipeline does not need to change.
            # It just passes the user's input to the smart script on the server.

            # --- Process Pedigree-Vision-BE ---
            BE_INDEX=${{ github.event.inputs.be_rollback_index }}
            echo "=================================================="
            echo ">>> Processing Pedigree-Vision-BE with index: $BE_INDEX"
            bash ~/rollback.sh 'Pedigree-Vision-BE' $BE_INDEX

            # --- Process PedigreeVisionUI ---
            UI_INDEX=${{ github.event.inputs.ui_rollback_index }}
            echo "=================================================="
            echo ">>> Processing PedigreeVisionUI with index: $UI_INDEX"
            bash ~/rollback.sh 'PedigreeVisionUI' $UI_INDEX

            # --- Process DigitreeModels ---
            MODELS_INDEX=${{ github.event.inputs.models_rollback_index }}
            echo "=================================================="
            echo ">>> Processing DigitreeModels with index: $MODELS_INDEX"
            bash ~/rollback.sh 'DigitreeModels' $MODELS_INDEX
            
            echo "=================================================="
            echo "All specified operations have been processed."
