name: EC2 Multi-Repo Rollback

on:
  workflow_dispatch:
    inputs:
      be_rollback_index:
        description: 'Pedigree-Vision-BE: How many versions to roll back by? (Use 0 to skip)'
        required: true
        type: number
        default: 0
      ui_rollback_index:
        description: 'PedigreeVisionUI: How many versions to roll back by? (Use 0 to skip)'
        required: true
        type: number
        default: 0
      models_rollback_index:
        description: 'DigitreeModels: How many versions to roll back by? (Use 0 to skip)'
        required: true
        type: number
        default: 0

jobs:
  trigger_multi_rollback:
    name: Trigger Rollbacks on EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute Conditional Rollbacks on EC2 Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            set -e # Stop the script if any rollback command fails

            # --- Process Pedigree-Vision-BE ---
            BE_INDEX=${{ github.event.inputs.be_rollback_index }}
            if [ "$BE_INDEX" -gt 0 ]; then
              echo "=================================================="
              echo ">>> Triggering rollback for Pedigree-Vision-BE by $BE_INDEX version(s)..."
              bash ~/rollback.sh 'Pedigree-Vision-BE' $BE_INDEX
            else
              echo "=================================================="
              echo ">>> Skipping rollback for Pedigree-Vision-BE (index is 0)."
            fi

            # --- Process PedigreeVisionUI ---
            UI_INDEX=${{ github.event.inputs.ui_rollback_index }}
            if [ "$UI_INDEX" -gt 0 ]; then
              echo "=================================================="
              echo ">>> Triggering rollback for PedigreeVisionUI by $UI_INDEX version(s)..."
              bash ~/rollback.sh 'PedigreeVisionUI' $UI_INDEX
            else
              echo "=================================================="
              echo ">>> Skipping rollback for PedigreeVisionUI (index is 0)."
            fi

            # --- Process DigitreeModels ---
            MODELS_INDEX=${{ github.event.inputs.models_rollback_index }}
            if [ "$MODELS_INDEX" -gt 0 ]; then
              echo "=================================================="
              echo ">>> Triggering rollback for DigitreeModels by $MODELS_INDEX version(s)..."
              bash ~/rollback.sh 'DigitreeModels' $MODELS_INDEX
            else
              echo "=================================================="
              echo ">>> Skipping rollback for DigitreeModels (index is 0)."
            fi
            
            echo "=================================================="
            echo "All specified rollbacks have been processed."
