name: SSH into EC2 and gather identity

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Update server
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass
          ping -c 5 ${{ secrets.EC2_HOST }}

      - name: Execute Commands on EC2 Server and Fetch IPs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            echo "Fetching public and private IPs..."
            PUBLIC_IP=$(curl -s ifconfig.me)
            PRIVATE_IP=$(hostname -I | awk '{print $1}')
            echo "PUBLIC_IP=$PUBLIC_IP" > ~/GitHub.env
            echo "PRIVATE_IP=$PRIVATE_IP" >> ~/GitHub.env
            cat ~/GitHub.env

      - name: Copy GitHub.env from EC2 to Runner
        run: |
          sshpass -p "${{ secrets.EC2_PASSWORD }}" scp -o StrictHostKeyChecking=no -P 22 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/GitHub.env GitHub.env

      - name: Echo contents of GitHub.env
        run: |
          echo "Contents of GitHub.env:"
          cat GitHub.env
