name: SSH into EC2 and gather identity

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:  # <- You missed this "steps" key
      - name: Execute Commands on EC2 Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            echo "==== HOSTNAME ===="
            hostname

            echo "==== IP ADDRESSES ===="
            ip addr show

            echo "==== META-DATA FIELDS ===="
            curl -s http://169.254.169.254/latest/meta-data/

            echo "==== INSTANCE ID ===="
            curl -s http://169.254.169.254/latest/meta-data/instance-id

            echo "==== IAM ROLE ===="
            curl -s http://169.254.169.254/latest/meta-data/iam/info
